name: pr2changelog
on:
  pull_request_target:
    paths-ignore:
      - "CHANGELOG.md"
    branches:
      - develop
    types:
      - closed
      - edited
      - opened

jobs:
  dry_check:
    if: github.event.pull_request.merged == false

    name: changelog generator dry check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check if draft
        id: is_draft
        run: echo "draft=${{ github.event.pull_request.draft }}" >> $GITHUB_ENV

      - name: Check title for [DRAFT]
        id: is_draft_title
        run: echo "draft_title=${{ contains(github.event.pull_request.title, '[DRAFT]') }}" >> $GITHUB_ENV
        
      - name: Check description for no-cl
        id: is_no_cl
        run: echo "no_cl=${{ contains(github.event.pull_request.body, 'no-cl') }}" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "draft=${{ env.draft }}"
          echo "draft_title=${{ env.draft_title }}"
          echo "no_cl=${{ env.no_cl }}"

      - name: pr2changelog
        id: pr2changelog
        uses: corp-0/pr2changelog@api-integration
        with:
          categories: Fix;New;Improvement;Balance
          write_to_file: false
        if: env.draft == 'false' || env.draft_title == 'false' || env.no_cl == 'false'
          
      - name: Comment PR
        if: ${{ steps.pr2changelog.outputs.found_changes == 0 && (env.draft == 'false' || env.draft_title == 'false' || env.no_cl == 'false') }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Your PR has no registered changes in its description!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  after_merge:
    if: github.event.pull_request.merged == true

    name: changelog generator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check if draft
        id: is_draft
        run: echo "draft=${{ github.event.pull_request.draft }}" >> $GITHUB_ENV

      - name: Check title for [DRAFT]
        id: is_draft_title
        run: echo "draft_title=${{ contains(github.event.pull_request.title, '[DRAFT]') }}" >> $GITHUB_ENV
        
      - name: Check description for no-cl
        id: is_no_cl
        run: echo "no_cl=${{ startsWith(github.event.pull_request.body, 'no-cl') }}" >> $GITHUB_ENV

      - name: pr2changelog
        id: pr2changelog
        uses: corp-0/pr2changelog@api-integration
        with:
          categories: Fix;New;Improvement;Balance
          write_to_file: false
          api_secret_token: ${{ secrets.CHANGELOG_API_SECRET }}
          api_url: "https://changelog.unitystation.org/register-change"
        if: env.draft == 'false' && env.draft_title == 'false' && env.no_cl == 'false'
          
      - name: Comment PR
        if: ${{ steps.pr2changelog.outputs.generated_changelog == 0 && (env.draft == 'false' || env.draft_title == 'false' || env.no_cl == 'false') }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Your PR was merged with no registered changes or there was a problem with the API caller.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
