name: pr2changelog
on:
  pull_request_target:
    paths-ignore:
      - "CHANGELOG.md"
    branches:
      - develop
    types:
      - closed
      - edited
      - opened

jobs:
  dry_check:
    if: github.event.pull_request.merged == false

    name: changelog generator dry check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pr2changelog
        id: pr2changelog
        uses: corp-0/pr2changelog@master
        with:
          categories: Fix;New;Improvement;Balance

  after_merge:
    if: github.event.pull_request.merged == true

    name: changelog generator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pr2changelog
        id: pr2changelog
        uses: corp-0/pr2changelog@master
        with:
          categories: Fix;New;Improvement

      - name: prepare files to push
        if: ${{ steps.pr2changelog.outputs.generated_changelog == 1 }}
        run: |
          mkdir output
          cp CHANGELOG.md output/CHANGELOG.md
          # cp CHANGELOG.json output/CHANGELOG.json

      - name: Push to changelog repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PR2CHANGELOG_TOKEN }}
        with:
          source-directory: output/changelod.md
          destination-github-username: unitystation
          destination-repository-name: changelog
          user-email: action@github.com
          target-branch: main
