name: Check Variable Placement

on:
  pull_request:
    paths:
      - '**/*.cs'

jobs:
  check-variables:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch base branch
      run: git fetch origin ${GITHUB_BASE_REF}:${GITHUB_BASE_REF}

    - name: Check Variable Placement
      run: |
        echo "Branch Name: ${{ github.event.pull_request.head.ref }}"
        base_sha=$(git rev-parse ${{ github.base_ref }})
        misplaced_variables=""
        grepResult=$(git diff --name-only $base_sha ${{ github.sha }} | grep '\.cs$' | xargs grep -n -P '^\s*(public|private|protected|internal|static)?\s+(\w+\s+)?\w+\s*=\s*[^{]*\{' | grep -v '^\s*//' | grep -v '^\s*}$' | grep -v -E 'get|set')
        if [ -z "$grepResult" ]; then
          echo "No misplaced variables found. grepresult is null or unset."
          exit 0
        else
          misplaced_variables=$grepResult
        fi

        echo "result of grep:"
        echo "$misplaced_variables"

        if [ -n "${misplaced_variables}" ] && [ -n "$misplaced_variables" ]; then
          echo "Misplaced variables found:"
          echo "$misplaced_variables"
          exit 1
        else
          echo "No misplaced variables found."
          exit 0
        fi
