name: Check Variable Placement

on:
  pull_request:
    paths:
      - '**/*.cs'

jobs:
  check-variables:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch base branch
      run: git fetch origin ${GITHUB_BASE_REF}:${GITHUB_BASE_REF}

    - name: Check Variable Placement
      run: |
        echo "Branch Name: ${{ github.event.pull_request.head.ref }}"
        base_sha=$(git rev-parse ${{ github.base_ref }})
        misplaced_variables=$(
            git diff --name-only $base_sha ${github.sha} |
            grep '\.cs$' |
            xargs sh -c 'cat >&2 && cat {} | sed -ne "/^/$/q; /class/{flag=1}; /^}/{flag=0}; /([a-zA-Z][^;\{]*=[^;\{]; flag/{ print }; p'" |
            tee /dev/stderr |
            grep -v '^\s*//' |
            grep -v 'get' |
            grep -v 'set' |
            awk '{if (match($0, /^[ \t]+([a-zA-Z][^:\{\}]+):/) {var_name=$1}} /^[ \t]+([a-zA-Z][^;\{]*)=(.*);/ {if (length(var_name)>0) print var_name ": " $0}' || echo "")
    
        if [ -n "$misplaced_variables" ]; then
          echo "Misplaced variables found:"
          echo "$misplaced_variables"
          exit 1
        else
          echo "No misplaced variables found."
          exit 0
        fi
    
